[smtp]
# 发送 smtp 地址端口
Host   = ""
Port   =
# 发送邮件邮箱账号密码
User   = ""
UserPW = ""

[monitor]
# 告警通知邮箱
NotifyMailList=['']
# 同类型事件告警邮件间隔 30 分钟
NotifyIntervalTime=30
# 三分钟检查一次
# 执行周期预设配置参考 https://pkg.go.dev/github.com/robfig/cron/v3#hdr-Predefined_schedules
RepeatTime = "@every 3m"
# cpu 最大使用率
MaxiMumCPU = 95
# 内存 最大使用率
MaxiMumNUM = 95
# 磁盘 最大使用率
MaxiMumDisk = 90

